"use client";

import { useState, useEffect } from "react";
import { albumConfig } from "@/app/data/albumConfig";
import { shuffleArray } from "@/lib/mediaUtils";
// Import static media list (generated by scripts/generateMediaList.js)
import mediaList from "@/app/data/mediaList.json";

export interface MediaItem {
  id: string;
  src: string;
  filename: string;
  type: "image" | "video";
  caption?: string;
}


export type AlbumContent = Record<string, MediaItem[]>;

export function useAlbumMedia() {
  const [media, setMedia] = useState<AlbumContent>({});
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    // Process the static media list
    const processedMedia: AlbumContent = {};

    Object.entries(mediaList as Record<string, string[]>).forEach(([folder, files]) => {
      let folderFiles = [...files];

      // Sort or Shuffle
      if (albumConfig.settings.randomOrder) {
        folderFiles = shuffleArray(folderFiles);
      } else {
        folderFiles.sort((a, b) => a.localeCompare(b));
      }

      processedMedia[folder] = folderFiles.map((filename) => {
        const ext = filename.split(".").pop()?.toLowerCase();
        const type = ["mp4", "mov", "webm"].includes(ext || "") ? "video" : "image";
        
        return {
          id: filename,
          filename,
          src: `/album-optimized/${folder}/${filename}`,
          type,
          caption: albumConfig.captions[filename] || undefined,
        };
      });
    });

    setMedia(processedMedia);
    setIsLoading(false);
  }, []);

  return { media, isLoading };
}
